### ISSUE TITLE
Your app is level 0

### ISSUE THREAD

**Issue by maniackcrudelis** [YunoHost-Apps/onlyoffice_ynh#12]
Your app is currently failing all tests on our CI.
https://ci-apps.yunohost.org/ci/job/2539

Unless the app is fixed before next Saturday, 13th, this app will be set at notworking.

**Comment by nath5394** [comment]
App is labeled level 7 actually, maybe this issue could be closed 😉 or maybe there is something wich needs to be fixed (CI fails https://ci-apps.yunohost.org/ci/apps/onlyoffice/ )

**Comment by maniackcrudelis** [comment]
This issue is 3 months old, feel free to close it as the app is no longer level 0.

**Comment by decentral1se** [comment]
@YunoHost-Apps/apps-group, can I get permissions to manage this repository?

This is resolved, see https://dash.yunohost.org/appci/app/onlyoffice.

**Comment by maniackcrudelis** [comment]
Done
