### ISSUE TITLE
Update not working anymore on arm64

### ISSUE THREAD

**Issue by Quiwy** [YunoHost-Apps/onlyoffice_ynh#124]
### Describe the bug

It's not possible anymore to update onlyoffice on arm64 architecture with version 8.0.1~ynh1 

### Context

- Hardware: odroid hc4
- YunoHost version: 11.2.11.2
- I have access to my server: yes
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- If upgrading, current package version: 7.5~ynh1

### Steps to reproduce

-Try to update to  8.0.1~ynh1 

### Expected behavior

Update working

### Logs

`Cette application ne peut être installée que sur les architectures amd64. L'architecture de votre serveur est arm64`.

Not sure but maybe adding arm64 arch to [manifest.yml](https://github.com/YunoHost-Apps/onlyoffice_ynh/blob/master/manifest.toml#L23) could help ?

**Comment by ndx1905-github** [comment]
I have the same error. Is it possible that it’s just an error of the configuration file of the ynh package that would unduly restrict target and exclude arm ? (It’s not unusual)

![IMG_1682](https://github.com/YunoHost-Apps/onlyoffice_ynh/assets/64833823/15bfdac2-a43c-4819-9f47-7211bc8fbcec)
![IMG_1683](https://github.com/YunoHost-Apps/onlyoffice_ynh/assets/64833823/1a0f6146-6e54-4d77-bfba-39a20c6cdc06)
![IMG_1685](https://github.com/YunoHost-Apps/onlyoffice_ynh/assets/64833823/d072e046-2bc7-49c6-b124-c10ac21e9de5)
![IMG_1687](https://github.com/YunoHost-Apps/onlyoffice_ynh/assets/64833823/41dc533e-3730-4008-93ab-c43f1fcda3f2)

**Comment by Quiwy** [comment]
Fixed with #125 and new version 8.0.1~ynh2.
Thanks @kay0u for the merge :heart:
