### ISSUE TITLE
installation failed due to package dependency issue

### ISSUE THREAD

**Issue by rocky-III** [YunoHost-Apps/onlyoffice_ynh#20]
installation failed - please have a look at the logs:
https://paste.yunohost.org/raw/firotezogo
thanks

**Comment by decentral1se** [comment]
> 2019-08-27 12:39:02,434: DEBUG - + dpkg --force-depends -i ./onlyoffice-ynh-deps_5.2.8ynh1_all.deb
> 2019-08-27 12:39:03,144: DEBUG - (Reading database ... 56583 files and directories currently installed.)
> 2019-08-27 12:39:03,254: DEBUG - Preparing to unpack .../onlyoffice-ynh-deps_5.2.8ynh1_all.deb ...
> 2019-08-27 12:39:03,359: DEBUG - Unpacking onlyoffice-ynh-deps (5.2.8ynh1) over (5.2.8ynh1) ...
> 2019-08-27 12:39:03,766: DEBUG - dpkg: onlyoffice-ynh-deps: dependency problems, but configuring anyway as you requested:
> 2019-08-27 12:39:03,774: DEBUG -  onlyoffice-ynh-deps depends on onlyoffice-documentserver; however:
> 2019-08-27 12:39:03,777: DEBUG -   Package onlyoffice-documentserver is not installed.
> 2019-08-27 12:39:03,780: DEBUG - 
> 2019-08-27 12:39:03,791: DEBUG - Setting up onlyoffice-ynh-deps (5.2.8ynh1) ...

So, looks like a package dependency issue.

**Comment by rocky-III** [comment]
what can I do? 
i´m using a selfhostet cubitruck yunohost installation

**Comment by decentral1se** [comment]
Hey @rocky-III, I'm not exactly sure but you need to take a look at what is being installed and try to manually resolve the conflict issue from the command line. For example, you might try to see if you can `apt remove --purge --autoremove onlyoffice-documentserver`. 

The package is doing this during installation:

https://github.com/YunoHost-Apps/onlyoffice_ynh/blob/07c565b882c288a4490302f2123dc0dc1e76a74e/scripts/install#L60-L80

**Comment by decentral1se** [comment]
Also worth looking at is https://github.com/YunoHost-Apps/onlyoffice_ynh/issues/18#issuecomment-511521739.

**Comment by rocky-III** [comment]
Thanks

I tried it:
```
root@my:~# apt remove --purge --autoremove onlyoffice-documentserver                             
Reading package lists... Done                                                                    
Building dependency tree                                                                         
Reading state information... Done                                                                
E: Unable to locate package onlyoffice-documentserver                                            
root@my:~#  
```                                                                                     

I´m not so firm in installing extra stuff besides using the yunohost pakages
I´m on yunohost armbian installation
https://www.armbian.com/cubietruck/
so do you think i can try
`apt install postgresql libstdc++6 redis-server rabbitmq-server libcurl4-nss-dev`
or do I have to change some thing?

**Comment by decentral1se** [comment]
Sure, the package installer can't find the package because you need to enable the extra repository first. If you want to investigate that, there is decent documentation [over here](https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx).

So, yes, you could try to install those dependencies (postgresql, libstdc... etc.) and see if you see any problems. Then try to run the `yunohost app install ...` and make sure to pass the `--debug` flag.

I've just installed this package on a fresh machine and had success, so it appears to be in working order in the general case.

**Comment by decentral1se** [comment]
> so do you think i can try `apt install postgresql libstdc++6 redis-server rabbitmq-server libcurl4-nss-dev`
or do I have to change some thing?

Aha, I ran into this very issue and this worked for me :sun_with_face: 

I believe it has to do with the fact that the installer uses an old (Debian Squeeze) apt repository which turns out to include some conflict with a newer package. However, if we install it first, before we install only office, then the app installation skips this conflict.

**Comment by rocky-III** [comment]
I tried it but the installation still did not work
please have a look:
https://paste.yunohost.org/raw/osasujutiw
thanks

**Comment by decentral1se** [comment]
Argh, unfortunate! OK, I would then recommend to manually run the installation of the onlyoffice dependencies and then the official package as well to try and trigger the error yourself. From https://helpcenter.onlyoffice.com/server/linux/document/linux-installation.aspx:

```bash
$ rm /etc/apt/sources.list.d/onlyoffice.list && apt update  # if it already is there
$ apt install postgresql libstdc++6 redis-server rabbitmq-server libcurl4-nss-dev
$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys CB2DE8E5
$ sudo echo "deb https://download.onlyoffice.com/repo/debian squeeze main" | sudo tee /etc/apt/sources.list.d/onlyoffice.list
$ apt update
$ apt install onlyoffice-documentserver
```

At this point, you should see some installation failure with more information.

**Comment by alexAubin** [comment]
Closing because issue is getting old and not sure what's the exact issue ... package evolved recently so might be fixed.
