### ISSUE TITLE
Avoid editing the internal NGINX configurations during install

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/onlyoffice_ynh#23]
I'm sure there's a good reason for what happens here : 

https://github.com/YunoHost-Apps/onlyoffice_ynh/blob/07c565b882c288a4490302f2123dc0dc1e76a74e/scripts/install

but it's really not recommended to proceed that way ... The nginx configuration is going to be marked as manually modified, and will therefore not be updated to Yunohost's standard, and might even trigger bugs later like in https://forum.yunohost.org/t/nginx-ne-demarre-plus/9175 ... :confused:

**Comment by alexAubin** [comment]
Another user had this issue today ...

**Comment by ImaCrea** [comment]
oups I was about to install it, I'll wait for a bit then :) Thanks <3

**Comment by decentral1se** [comment]
I won't be getting around to this soon, so if anyone has time, please go for it. I'm not sure how to resolve it since OnlyOffice seems to need this addition in the upstream configuration.

**Comment by SimonMellerin** [comment]
Hi,

If I've installed this app and want to get back to a normal config (ie don't mark as manually modified) How can I proceed ?

Thanks !

**Comment by decentral1se** [comment]
Hi @SimonMellerin you can use the `regen-conf` --force command I think? I think that is under `yunohost tools` on the command-line but I am really not sure. You might also ask on the support channels...

**Comment by alexAubin** [comment]
Not sure who's maintaining this app, but note that the current hack won't work anymore in 3.8 because we will now include security settings in domain confs from a global security.conf.inc ...

Anyway less-hackish version should be found ... In particular, because we set the header with `more_set_headers` (though this wasnt the case in the past) I believe it should be possible to supersede the header in the app conf directly.

**Comment by alexAubin** [comment]
Follow-up for this bug. 

New hack explained here was found to work (basically just re-add the same line) :  https://forum.yunohost.org/t/suite-a-maj-nextcloud-et-onlyoffice-bloque-par-la-politique-x-frame-options/11665/6

But I don't understand why we can't just add this line in onlyoffice's nginx.conf directly (in fact there's already one line ... maybe it's just about changing add_header to more_set_header)

**Comment by alexAubin** [comment]
Should be fixed by https://github.com/YunoHost-Apps/onlyoffice_ynh/pull/39
