### ISSUE TITLE
Install fails because of rabbitmq-server "process_not_running"

### ISSUE THREAD

**Issue by EpicTGuy** [YunoHost-Apps/onlyoffice_ynh#30]
https://paste.yunohost.org/raw/qemulucuto

Someone can help me ?

**Comment by decentral1se** [comment]
Perhaps another another variant of https://github.com/YunoHost-Apps/onlyoffice_ynh/issues/20?

**Comment by EpicTGuy** [comment]
https://paste.yunohost.org/raw/eyovoqater

No I have allready try this issue...

<img width="1440" alt="Capture d’écran 2020-03-27 à 19 09 52" src="https://user-images.githubusercontent.com/20190654/77786707-8c38f080-705e-11ea-97d7-c9124bf65062.png">

<img width="1440" alt="Capture d’écran 2020-03-27 à 19 08 04" src="https://user-images.githubusercontent.com/20190654/77786551-4b40dc00-705e-11ea-8f79-d549ba84941e.png">
I think this is a problem with rabbitMQ, but I don't know can I solve it...

**Comment by EpicTGuy** [comment]
I think it's a problem with my hostnames
I choose office.hostnam.ltd, my nextcloud hostname is cloud.hostname.ltd and my hostname by default is perso.hostname.ltd
And the path of onlyofffice in yunohost is only "/". Do you think the problem can come from somwhere here ?

**Comment by EpicTGuy** [comment]
Even if i try with my perso.hostname.ltd and the path by default /onlyoffice I have the same problem
I allready try with my hostname in place of localhost in /etc/hosts...

**Comment by alexAubin** [comment]
After being able to reproduce the issue today, the explanation is that rabbitmq-server is fucking stupid and miserably crash if the short hostname is not in /etc/hosts

A fix will be provided in Yunohost 3.8

In the meantime, running this command should do the trick : 

```
echo -e "127.0.0.1\t$(hostname -s)" >> /etc/hosts
```
