### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by guillaume84250** [YunoHost-Apps/onlyoffice_ynh#4]
Hello
Install failed for me 
[https://paste.yunohost.org/raw/lutagesebo](url)

**Comment by liberodark** [comment]
oui je vois le soucis !

**Comment by liberodark** [comment]
Faudrait essayer de tester sans rabbitmq mais cela me parait bizzare quand meme

**Comment by guillaume84250** [comment]
Bonsoir, comment faire sans rabbitmq ?

**Comment by liberodark** [comment]
Bonjour,

Je vais faire une version test genre beta une branche

**Comment by guillaume84250** [comment]
OK, ça marche. Dès que je rentre à la maison je test et je les log ici

**Comment by guillaume84250** [comment]
Bonsoir, voici les log sur putty

![onlyoffice](https://user-images.githubusercontent.com/44683351/49036158-3c6ebe80-f1b7-11e8-8109-be1ab9d19e81.PNG)

Et voici le résultats sur le web

![onlyoffice1](https://user-images.githubusercontent.com/44683351/49036299-9ff8ec00-f1b7-11e8-8852-cc390771f75a.PNG)

**Comment by liberodark** [comment]
oui je pense que cela vient du fait qu'il faut une instance neuve est vraiment clean

**Comment by guillaume84250** [comment]
OK merci

**Comment by liberodark** [comment]
Tenez moi au courant svp
