### ISSUE TITLE
OnlyOffice 6 is released

### ISSUE THREAD

**Issue by dosch** [YunoHost-Apps/onlyoffice_ynh#46]
https://helpcenter.onlyoffice.com/installation/docs-changelog.aspx

**Comment by ericgaspar** [comment]
OnlyOffice is installed from a repository which itself is continuously updated. The version number of the Readme does not reflect the version installed. If you install now, version 6.0.1 is installed.

**Comment by tomdereub** [comment]
Ok, but how to update when the app is already installed ? I have Onlyoffice version 5.5.
Do I need to remove and reinstall the app ?

**Comment by tomdereub** [comment]
Actually it works, I've just removed onlyoffice, and then reinstalled, and I have now the version 6 installed, thanks !
Is it possible to include these updates in the package ? I mean, we could see that updates are available in the webadmin, and just click there to update ?

**Comment by dosch** [comment]
@tomdereub and did that not remove all your docs on the document server?

**Comment by tomdereub** [comment]
No, all docs are stored by nextcloud. Nextcloud just calls onlyoffice to open docs online, but the app onlyoffice itself doesn't store any document.

**Comment by alexAubin** [comment]
Closing because just yolomerged the testing PR which bumps the version number (though as explained by Eric, the version in our manifest doesn't reflect the exact version installed because apt may propose and upgrade for the corresponding .deb independently from Yunohost)
