### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by isAAAc** [YunoHost-Apps/onlyoffice_ynh#5]
https://paste.yunohost.org/raw/tuceqaxagi  
```
  YNH_APP_ARG_DOMAIN: krashboyz.org
  YNH_APP_ARG_PATH: /onlyoffice
```
j'ai l'impression qu'il prend pas YNH_APP_ARG_PATH en compte ?

voir : 
```
2018-11-23 00:08:18,534: DEBUG - + ynh_webpath_available krashboyz.org /
2018-11-23 00:08:18,535: DEBUG - + local domain=krashboyz.org
2018-11-23 00:08:18,535: DEBUG - + local path=/
2018-11-23 00:08:18,535: DEBUG - + sudo yunohost domain url-available krashboyz.org /
2018-11-23 00:08:19,036: DEBUG - False
2018-11-23 00:08:19,037: DEBUG - + ynh_webpath_register onlyoffice krashboyz.org /
2018-11-23 00:08:19,037: DEBUG - + local app=onlyoffice
2018-11-23 00:08:19,037: DEBUG - + local domain=krashboyz.org
2018-11-23 00:08:19,037: DEBUG - + local path=/
2018-11-23 00:08:19,038: DEBUG - + sudo yunohost app register-url onlyoffice krashboyz.org /
2018-11-23 00:08:19,539: WARNING - Cette URL n’est pas disponible ou est en conflit avec une application existante
```

**Comment by Aguay-val** [comment]
Bonjour,
Je pense que c'est parce qu'il y a déjà une application sur le "/" de ton yunohost.
Sur l'url krashboyz.org.
Pour le moment, le script d'installation ne supporte pas l'installation en subdirectory donc il est obligatoire d'avoir un domaines différent pour onlyoffice.

**Comment by isAAAc** [comment]
Bonjour, 
oui, c'est ça, pourtant , il demande un subdirectory lors de l'install qu'il utilise dans la variable YNH_APP_ARG_PATH  , mais il n'en tient absolument pas compte lors du reste de l'install, d'où mon ticket ;)

**Comment by liberodark** [comment]
En somme c'est assez simple OnlyOffice supporte pas pour l'instant le /onlyoffice mais j'ai ajouté le support dans le script d'install en attendant car si on trouvent une solution elle sera publié onlyoffice est très difficile et capricieux il faut presque l'installer tout seule d'ailleurs je recommande pas d'autres apps à coté de onlyoffice certaines apps ne fonctionne plus avec du moins onlyoffice ne se lance plus avec certains apps installé.

**Comment by isAAAc** [comment]
quelles apps par exemple, ça peut être pertinent de l'indiquer dans le readme.md non ? idem pour le fait qu'il lui faille un domaine dédié pour le moment.

**Comment by liberodark** [comment]
Cet déjà indiqué dans le manifeste

**Comment by isAAAc** [comment]
je pense que l'ajouter dans le readme.md (comme dans 'autres applications) le rendrait plus visible et éviterait qu'on tente de l'installer sur la racine, 
d'ailleurs, d'autres applications indiquent lors de l'installation que si ce n'est pas à la racine du ndd, l'install ne peut pas continuer.
Le fait que le point de montage soit demandé (sans autre retour backlog) laisse penser que le faire est possible puisque le systeme le permet lors de l'installation.

**Comment by liberodark** [comment]
Désolé mais le message est explicite lors de l'installation vu que cela pourrait changer c'est ainsi actuellement
