### ISSUE TITLE
Cannot install from RPi3 Yunohost

### ISSUE THREAD

**Issue by Lastorder-DC** [YunoHost-Apps/onlyoffice_ynh#52]
**Describe the bug**
I tried to install onlyoffice from yunohost(RPi3) but It failed.

**Versions**
- Hardware: Raspberry Pi 3
- YunoHost version: 4.1.6
- I have access to my server: Through SSH + through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: no
- Using, or trying to install package version/branch: 6.0.1~ynh1

**To Reproduce**
    ```sh
    sudo yunohost app install onlyoffice
    ```

**Expected behavior**
onlyoffice installed.

**Logs**
From web: https://paste.yunohost.org/raw/vowayovowo
From cli: https://paste.yunohost.org/raw/eboborecef

**Comment by alexrjs** [comment]
Same with raspi4 and latest yunohost for raspi... Seems it does not work because of the missing arm support for the documentserver from onlyoffice... So there should be at least a version check before doing all the install or at least label it not working for arm. :-/

> Warning: Package onlyoffice-documentserver is not available, but is referred to by another package.
> Warning: This may mean that the package is missing, has been obsoleted, or
> Warning: is only available from another source
> Warning: E: Package 'onlyoffice-documentserver' has no installation candidate
> Warning: Unable to install dependencies
> Error: Unable to install onlyoffice: An error occurred inside the app installation script

**Comment by alexAubin** [comment]
Closing, c.f. https://github.com/YunoHost-Apps/onlyoffice_ynh/issues/55
