### ISSUE TITLE
Support for ARM architecture

### ISSUE THREAD

**Issue by Clemorange22** [YunoHost-Apps/onlyoffice_ynh#55]
**Describe the bug**
It's actually impossible to install Onlyoffice on ARM architecture 

**Versions**
- Hardware: Raspberry Pi at home / ARM architecture

**To Reproduce**
Just go to Yunohost app catalog and try to install OnlyOffice

**Expected behavior**
Install withouth any problem

There is actually a tutorial on the nextcloud forum to install OnlyOffice on RPi using qemu
https://help.nextcloud.com/t/tutorial-installing-onlyoffice-server-on-raspberry-pi-4-ubuntu-server-20-10/100739

It is possible to make it a "Yunohost" script ?

*Sorry for my bad english*

**Comment by tr1p0p** [comment]
I confirm i have a error when installing to RPI 4 arm64
Paste just here : https://paste.yunohost.org/raw/emixebaris

**Comment by alexAubin** [comment]
@Clemorange22 : reading the instructions, they start with : 

```
apt install qemu binfmt-support qemu-user-static
dpkg --add-architecture amd64
```

which sounds super spooky and experimental and resource-heavy ... Maybe this would work, but I would absolutely not run this on a production server that's running other apps ...

For anybody interested, the official discussion on OnlyOffice's upstream is here : https://github.com/ONLYOFFICE/DocumentServer/issues/152

**Comment by alexAubin** [comment]
I'm flagging as "wontfix" because there's not much that can be done until the upstream supports it. 

I added a check in the install script such that it's a bit more obvious : https://github.com/YunoHost-Apps/onlyoffice_ynh/commit/062cc7231a4ab644e4a251ca744f8f985b77c4d8

**Comment by Clemorange22** [comment]
Ok, thanks, so I think I will use Collabora online CODE server built-in nextcloud instead.
https://apps.nextcloud.com/apps/richdocumentscode_arm64
Does yunohost support well debian/ubuntu ?

**Comment by alexAubin** [comment]
>Does yunohost support well debian/ubuntu ?

Yunohost can be installed on top of Debian, yes, but the image we ship for Raspberry Pi is based on Raspbian. I have currently 0 experience with running Debian on an ARM board.

**Comment by Gredin67** [comment]
can someone confirm it's solved ? At least for arm64 ? https://github.com/ONLYOFFICE/DocumentServer/blob/master/CHANGELOG.md#710

**Comment by Clemorange22** [comment]
I can confirm this issue is solved.I've been able to install onlyoffice on my pi and to link it with my nextcloud instance.
