### ISSUE TITLE
Upgrade failded

### ISSUE THREAD

**Issue by nath5394** [YunoHost-Apps/onlyoffice_ynh#6]
Hello, 
The upgrade failed (from master). 
Here the output https://paste.yunohost.org/raw/ufiyutahad
The seems to be this line : https://github.com/YunoHost-Apps/onlyoffice_ynh/blob/9eee4dcb9f7602247981b4ba2a7ca7ab12634c26/scripts/upgrade#L22

The variable is null. 
I don't know if this variable is used only by your package or by all Yunohost...

**Comment by liberodark** [comment]
yes upgrade option is not working !
Now

**Comment by nath5394** [comment]
Hello, I reinstalled. But now I have this error : 
![capture d ecran du 2019-02-05 20-39-42](https://user-images.githubusercontent.com/7300309/52299721-77932800-2986-11e9-89ec-32390a2c64f8.png)

Do you think it is an error related to Onlyoffice or to Yunohost/SSO/Core ?

**Comment by nath5394** [comment]
I found in the browser console this error : 
`La ressource à l’adresse « https://cloud.monsite.com/yunohost/sso/?r=aHR0cHM6Ly9jbG91ZC5oYW5uZWJlcnQuY29tL3luaHBhbmVsLmpz » a été bloquée en raison d’un type MIME (« text/html ») incorrect (X-Content-Type-Options: nosniff).`

I think there is a problem with the header in nginx conf files. I don't know if this comme from nextcloud or onlyoffice domain conf file.

**Comment by yalh76** [comment]
this PR solve the update: https://github.com/YunoHost-Apps/onlyoffice_ynh/pull/9 and the connection error from nextcloud
