### ISSUE TITLE
the documenttype parameter for the config object is invalid

### ISSUE THREAD

**Issue by tutle** [YunoHost-Apps/onlyoffice_ynh#68]
Hello
Just update the onlyoffice plugin to 7.2.0 in my 22.2.0 nextcloud instance on yunohost server (with onlyoffice application 6.4.0~ynh2 ).
It was perfectly working before
Any suggestion ?
![onlyoffice error](https://user-images.githubusercontent.com/23037149/144298757-a2311220-ccc1-4b27-bc09-686d5a57f1eb.jpg)

**Comment by tutle** [comment]
No more developpment ? Sad... The problem persist on nextcloud 22.2.3~ynh1

**Comment by farvardin** [comment]
@tutle j'ai eu le même problème, il suffit de désinstaller onlyoffice, puis de le réinstaller !

EN: I had the same problem, just uninstall onlyoffice, then reinstall it!

**Comment by tutle** [comment]
Super, j'essaie dès demain !!! Merci !!!

**Comment by tutle** [comment]
Perfect, solved. Thanks a lot.
