### ISSUE TITLE
Fixe Relsease

### ISSUE THREAD

**Issue by liberodark** [YunoHost-Apps/onlyoffice_ynh#8]
Need to work on fixe release for run correctly this app and secure install for more good install.
Now installer install OnlyOffice with official step to install app have try installer with fixe release but not work :(

Need your help

**Comment by nath5394** [comment]
How can I help ?

**Comment by liberodark** [comment]
Yes need to make better script install with just deb and not source.list

**Comment by yalh76** [comment]
Hi @liberodark, I will try to fix it, I had one onlyoffice server working since last update.

**Comment by yalh76** [comment]
I worked to apply example_ynh + fixe all scripts on https://github.com/YunoHost-Apps/onlyoffice_ynh/pull/9

I will look how to fix the release

**Comment by yalh76** [comment]
release fixed with https://github.com/YunoHost-Apps/onlyoffice_ynh/pull/9
