### ISSUE TITLE
OnlyOffice failed to installed due to "Error inside Installation Script"

### ISSUE THREAD

**Issue by nmwander** [YunoHost-Apps/onlyoffice_ynh#94]
### Describe the bug

*OnlyOffice failed to installed due to "Error inside Installation Script"*

### Context

- Hardware: VPS
OS: Debian 11 (64-bit)
Processor: 2 x 1.8 GHz
Memory: 4096 MB
Storage: 40 GB

- YunoHost version: 11.1.6.2 (stable)
- 
- I have access to my server: through the webadmin

- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

- Using, or trying to install package version/branch:  7.1.0~ynh1

### Steps to reproduce

- If the error occurs in your browser, explain what you did:*
   1. Set up new VPS server
   2. Install yunohost
   3. Install OnlyOffice

### Expected behavior

Complete installation

### Logs

[https://paste.yunohost.org/raw/esiqodehox](https://paste.yunohost.org/raw/esiqodehox)

------------------------------

Apologize for the brevity, I am not sure how to detail more information.

**Comment by SiM** [comment]
I think I had the same issue and solved it this way:
- Install supervisor package (CLI): `apt install supervisor` 
- Install OnlyOffice

**Comment by nmwander** [comment]
Thank you for your suggestion.
Unfortunately, it doesn't seem to be working for me.

[https://paste.yunohost.org/raw/gagozilame](https://paste.yunohost.org/raw/gagozilame)

**Comment by nmwander** [comment]
Then I tried again recently, and now I can install it. Not sure what happen
Anyway, big thanks for SiM
